manifest:
  remotes:
    - name: ALpotato
      url-base: https://github.com/ALpotato
  projects:
     - name: zmk
       remote: ALpotato
       revision: ptdevice-cirque
       import: app/west.yml
  self:
    path: config
